banned-worlds:
  - world
  - world_resource
  - world_the_end
  - world_nether
banned-commands:
  - "/maphide"
  - "/squaremap:map hide"
  - "/dungeon"
  - "/dxl"
  - "/dungeons"
  - "/pw"
  - "/playerwarp"
  - "/tfly"
commands-on-war-start:
  - "mapshow"
  - "tfly"
commands-on-login:
  - "mapshow"
townwar-declaration-book:
  1:
    - "<dark_red>╔═╬<black>☠</black>╬═══╬<black>☠</black>╬═╗"
    - ""
    - "      <dark_red><bold>SCROLL INDEX</bold></dark_red>"
    - "   <dark_gray>(Click to navigate)"
    - " "
    - "<bold><color:#BEA50C>⬩<dark_red> <click:change_page:'2'>INTRO</click>"
    - " "
    - "<bold><color:#BEA50C>⬩<dark_red> <click:change_page:'4'>MECHANICS</click>"
    - " "
    - "<bold><color:#BEA50C>⬩<dark_red> <click:change_page:'9'>WAR STATS</click>"
    - " "
    - "<bold><color:#BEA50C>⬩<dark_red> <click:change_page:'11'>WAR REASONING</click> </bold>"
    - ""
    - "<dark_red>╚═╬<black>☠</black>╬═══╬<black>☠</black>╬═╝"
  2:
    - "<dark_red>╔═╬<black>☠</black>╬═══╬<black>☠</black>╬═╗"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "       <dark_red><bold>WAR INTRO"
    - "  <dark_gray>Usage, Date, & Sides"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "<dark_red>╚═╬<black>☠</black>╬═══╬<black>☠</black>╬═╝"
  3:
    - ""
    - "%server_time_MMMM d, Y%"
    - " "
    - "The town of <dark_red><declarer-name></dark_red> officially declared war on <dark_red><target-name></dark_red>."
    - " "
    - "The war will start as soon as <declarer-name> runs <gold>/t war declare</gold> while holding this book."
    - " "
  4:
    - "<dark_red>╔═╬<black>☠</black>╬═══╬<black>☠</black>╬═╗"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "       <dark_red><bold>MECHANICS"
    - "   <dark_gray>How the war works"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "<dark_red>╚═╬<black>☠</black>╬═══╬<black>☠</black>╬═╝"
  5:
    - "Each town starts with <dark_green><bold>100 HP</bold></dark_green>"
    - "and each resident in both towns will get a total of <gold>3 lives</gold>"
    - " "
    - "When the HP reaches <red><bold>0</bold></red>, that town loses the war."
    - "<dark_gray>(More on next page)"
  6:
    - "If a resident is killed in the war, their town loses <dark_red><bold>5 HP</bold></dark_red>"
    - " "
    - "If a resident dies naturally, their town loses <dark_red><bold>3 HP</bold></dark_red>"
    - " "
    - "If a resident uses a totem, their town loses <dark_red><bold>1 HP</bold></dark_red>"
    - " "
    - "<dark_gray>(More on next page)"
  regain:
    - "Every day, residents get <bold><dark_green>+3</dark_green></bold> lives (up to 6 max), and both towns lose <dark_red><bold>20 HP</bold></dark_red>."
    - " "
    - "Every <gold>20 minutes</gold>, your town regains HP depending on how many players are online."
    - " "
  rewards:
    - "After the war is over, the winner will get <bold><dark_red>HALF</dark_red></bold> of the loser's town balance!"
    - " "
    - "Additionally, they will also gain <gold>25%</gold> of the enemy's claims in the form of bonus claims!"
  7:
    - "<dark_red>╔═╬<black>☠</black>╬═══╬<black>☠</black>╬═╗"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "       <dark_red><bold>WAR STATS"
    - "  <dark_gray>Know your enemies..."
    - ""
    - ""
    - ""
    - ""
    - ""
    - "<dark_red>╚═╬<black>☠</black>╬═══╬<black>☠</black>╬═╝"
  8:
    - "The currrent stats of each of the towns: "
    - ""
    - "<dark_red><bold><declarer-name>"
    - "  <bold><color:#BEA50C>⬩<red></bold> Balance: <declarer-balance> Gold"
    - "  <bold><color:#BEA50C>⬩<red></bold> Size: <declarer-blocks>"
    - "  <bold><color:#BEA50C>⬩<red></bold> Residents: <declarer-residents>"
    - " "
    - "<dark_red><bold><target-name>"
    - "  <bold><color:#BEA50C>⬩<red></bold> Balance: <target-balance> Gold"
    - "  <bold><color:#BEA50C>⬩<red></bold> Size: <target-blocks>"
    - "  <bold><color:#BEA50C>⬩<red></bold> Residents: <target-residents>"
  9:
    - "<dark_red>╔═╬<black>☠</black>╬═══╬<black>☠</black>╬═╗"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "   <dark_red><bold>REASON & TERMS"
    - "  <dark_gray>Written by the mayor"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "<dark_red>╚═╬<black>☠</black>╬═══╬<black>☠</black>╬═╝"
nationwar-declaration-book:
  1:
    - "<dark_red>╔═╬<black>☠</black>╬═══╬<black>☠</black>╬═╗"
    - ""
    - "      <dark_red><bold>SCROLL INDEX</bold></dark_red>"
    - "   <dark_gray>(Click to navigate)"
    - " "
    - "<bold><color:#BEA50C>⬩<dark_red> <click:change_page:'2'>INTRO</click>"
    - " "
    - "<bold><color:#BEA50C>⬩<dark_red> <click:change_page:'4'>MECHANICS</click>"
    - " "
    - "<bold><color:#BEA50C>⬩<dark_red> <click:change_page:'9'>WAR STATS</click>"
    - " "
    - "<bold><color:#BEA50C>⬩<dark_red> <click:change_page:'11'>WAR REASONING</click> </bold>"
    - ""
    - "<dark_red>╚═╬<black>☠</black>╬═══╬<black>☠</black>╬═╝"
  2:
    - "<dark_red>╔═╬<black>☠</black>╬═══╬<black>☠</black>╬═╗"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "       <dark_red><bold>WAR INTRO"
    - "  <dark_gray>Usage, Date, & Sides"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "<dark_red>╚═╬<black>☠</black>╬═══╬<black>☠</black>╬═╝"
  3:
    - ""
    - "%server_time_MMMM d, Y%"
    - " "
    - "The nation of <dark_red><declarer-name></dark_red> officially declared war on <dark_red><target-name></dark_red>."
    - " "
    - "The war will start as soon as <declarer-name> runs <gold>/t war declare</gold> while holding this book."
    - " "
  4:
    - "<dark_red>╔═╬<black>☠</black>╬═══╬<black>☠</black>╬═╗"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "       <dark_red><bold>MECHANICS"
    - "   <dark_gray>How the war works"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "<dark_red>╚═╬<black>☠</black>╬═══╬<black>☠</black>╬═╝"
  5:
    - "Each nation starts with <dark_green><bold>100 HP</bold></dark_green>"
    - "and each resident in both nations will get a total of <gold>3 lives</gold>"
    - " "
    - "When the HP reaches <red><bold>0</bold></red>, that nation loses the war."
    - "<dark_gray>(More on next page)"
  6:
    - "If a resident is killed in the war, their nation loses <dark_red><bold>5 HP</bold></dark_red>"
    - " "
    - "If a resident dies naturally, their nation loses <dark_red><bold>3 HP</bold></dark_red>"
    - " "
    - "If a resident uses a totem, their nation loses <dark_red><bold>1 HP</bold></dark_red>"
    - " "
    - "<dark_gray>(More on next page)"
  regain:
    - "Every day, residents get <bold><dark_green>+3</dark_green></bold> lives (up to 6 max), and both nations lose <dark_red><bold>20 HP</bold></dark_red>."
    - " "
    - "Every <gold>20 minutes</gold>, your nation regains HP depending on how many players are online."
    - " "
  rewards:
    - "After the war is over, the winner will get <bold><dark_red>HALF</dark_red></bold> of the loser's town balance!"
    - " "
    - "Additionally, they will also gain <gold>25%</gold> of the enemy's claims in the form of bonus claims!"
  8:
    - "<dark_red>╔═╬<black>☠</black>╬═══╬<black>☠</black>╬═╗"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "       <dark_red><bold>WAR STATS"
    - "  <dark_gray>Know your enemies..."
    - ""
    - ""
    - ""
    - ""
    - ""
    - "<dark_red>╚═╬<black>☠</black>╬═══╬<black>☠</black>╬═╝"
  9:
    - "The current stats of each of the nations:"
    - ""
    - "<dark_red><bold><declarer-name>"
    - "  <bold><color:#BEA50C>⬩<red></bold> Balance: <declarer-balance> Gold"
    - "  <bold><color:#BEA50C>⬩<red></bold> Size: <declarer-blocks>"
    - "  <bold><color:#BEA50C>⬩<red></bold> Residents: <declarer-residents>"
    - " "
    - "<dark_red><bold><target-name>"
    - "  <bold><color:#BEA50C>⬩<red></bold> Balance: <target-balance> Gold"
    - "  <bold><color:#BEA50C>⬩<red></bold> Size: <target-blocks>"
    - "  <bold><color:#BEA50C>⬩<red></bold> Residents: <target-residents>"
  10:
    - "<dark_red>╔═╬<black>☠</black>╬═══╬<black>☠</black>╬═╗"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "   <dark_red><bold>REASON & TERMS"
    - "  <dark_gray>Written by the mayor"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "<dark_red>╚═╬<black>☠</black>╬═══╬<black>☠</black>╬═╝"
townwar:
  delay: 1800
nationwar:
  delay: 1800
alliancewar:
  delay: 1800
breakable-blocks:
  - TNT
  - RESPAWN_ANCHOR
  - OBSIDIAN
  - CRYING_OBSIDIAN
  - ENCHANTING_TABLE
  - ENDER_CHEST
  - ANVIL
declaration-book-name: '<color:#BEA50C>⬩ <color:#AD240C>Writable Declaration Scroll <gray>(Write Reasoning!) <color:#BEA50C>⬩'
townwar-declaration-name: '<color:#BEA50C>⬩ <color:#AD240C>Town War Declaration Scroll <color:#BEA50C>⬩'
nationwar-declaration-name: '<color:#BEA50C>⬩ <color:#AD240C>Nation War Declaration Scroll <color:#BEA50C>⬩'
writable-declaration-lore:
  - ''
  - '<!i><yellow>Right-click<gray> this scroll to write'
  - '<!i><gray>your reasoning behind the <yellow>war!'
  - ''
messages:
  prefix: "<bold><red>U<white>L</bold> <gray>» "
  teleport-cancelled: '<red>You have an ongoing war! You cannot teleport anywhere!'
  cannot-use-skills-in-war: '<red>You cannot use active skills during a war!'
  banned-command: '<red>You may not use this command during wars!'
  must-specify-target: '<red>No target found! Please write the target''s name in order to create a war scroll!'
  not-enough-arguments: '<red>You must specify <args>'
  mayor-offline: '<red><yellow><name></yellow> is the mayor of <yellow><warring-name></yellow> and is currently offline! You can only make an offer if they''re online!'
  not-enough-money: '<red>You have that much money in your account to offer!'
  must-have-town: '<red>You must have a town to use this command!'
  cannot-declare-official-nation: '<red>You cannot declare a war on a non-official nation without a reason! Please open a ticket on <yellow>discord.unitedlands.org</yellow> to start the war!'
  must-be-nationwar: '<red>You must be in a nation war to offer a town!'
  town-not-in-nation: '<red>You cannot offer a town that''s not part of your nation!'
  must-have-nation: '<red>You must have a nation to use this command!'
  no-wars-found: '<red>You don''t have any wars...'
  not-an-ally: '<red>You can only join nations that you''re allied with!'
  ally-has-no-war: '<red>That ally does not have any ongoing wars!'
  ally-has-war: '<red>Your ally <ally> is going through a war! You can join and help them with <yellow>/n war join <ally> !'
  must-not-have-war: '<red>You cannot join another war, you already have an active war!'
  ally-joined-war: '<yellow><ally><red> joined the war as an ally of <yellow><nation>!'
  must-not-be-neutral: '<red>You cannot create a war scroll while neutral! Please disable neutrality first!'
  ongoing-war: '<red>You cannot create a new war scroll while you have an ongoing war!'
  on-cooldown: '<red>You fought too recently! You can''t declare another war yet.'
  not-enough-tokens: '<red>You cannot create a war scroll of this type! You need <cost> tokens first!'
  invalid-town-name: '<red>Town not found! Please enter the correct name!'
  invalid-declaration-book: '<red>You cannot use artifacts as war scrolls!'
  invalid-nation-name: '<red>Nation not found! Please enter the correct name!'
  must-be-mayor: '<red>Only mayors can use this command!'
  cannot-declare-on-self: '<red>You cannot declare war on your own town/nation!'
  cannot-declare-on-allies: '<red>Target is an ally! You cannot declare war on them...'
  only-mayors-can-sign: '<red>Only the mayor of <yellow><declarer-name><red> can sign this declaration book!'
  must-not-be-neutral-target: '<red>Target is neutral! You can only create scrolls for non-neutral enemies!'
  must-have-online-player: '<red>Your target must have at least 1 player online to declare a war!'
  must-declare-nationwar: '<red>You cannot declare a <yellow>town war</yellow> because both sides have nations! Declare a <yellow>nation war</yellow> instead!'
  ongoing-war-target: '<red>Target has an ongoing war! You cannot declare war on them!'
  invalid-held-book: '<red>You must be holding a <yellow>declaration scroll</yellow> to use this command'
  must-be-book-owner: '<red>Your town is not the owner of this declaration scroll!'
  war-won: '<green>Victory! The war has ended! You''ve won <bold><gold><money-amount></gold></bold> Gold from your enemy''s balance, and an extra <bonus-claims> bonus claims!'
  war-lost: '<red>You''ve lost the war... Your enemy has taken over <bold><gold><money-amount></gold></bold> Gold from your total balance, and they''ve earned <bonus-claims> bonus claims from you.'
  regular-death: '<red><victim> Player died! <victim-warrer> has lost <dark_red>3 hp!'
  player-killed: '<red><killer> killed <victim>! <victim-warrer> has lost <dark_red>5 health</dark_red> permanently!'
  player-killed-self: '<red><victim> has accidentally killed themselves! <victim-warrer> has lost <dar_red>5 health</dark_red> permanently!'
  totem-pop: '<red><victim> has popped a totem! <victim-warrer> lost 1 hp!'
  removed-from-war: '<red><victim> has lost all their lives for the day! They have been sent off to the jail of <yellow><jailer></yellow> to serve <yellow>3 hours</yellow>!'
  you-were-jailed: '<red>You''ve just lost your lives and got jailed! You will be un-jailed if your side can break you out of here! Alternatively, serve <yellow>3 hours!'
  no-pending-requests: '<red>You don''t have any pending surrender requests!'
  won-surrender-money: '<green>War won! You''ve earned <gold><money></gold> Gold in your town/nation balance!'
  lost-surrender-money: '<red>You''ve surrendered from the war... Your side has offered <gold><money> Gold</gold>, and the deal was accepted.'
  won-surrender-town: '<green>Victory! You''ve won the war, and accepted <yellow><town></yellow> as a surrender offer from your enemy. It is now a part of your nation!'
  lost-surrender-town: '<red>You''ve surrendered from the war... Your side has offered all of <yellow><town></yellow> to end the war, and the deal was accepted.'
  war-end-peace: '<green>The war has ended... Both sides agreed on a White Peace offer.'
  war-end-tie: '<green>The war has ended... Neither side won as they both reached 0 HP!'
  war-start-broadcast: '<yellow><declarer><red> has declared a war on <yellow><victim><red>! May the victor bring glory to their side!'
  surrender-received: '<red>You received a surrender request from <yellow><requester></yellow>! They have offered <yellow><offer></yellow> in order to end this war! Do <yellow>/surrender accept</yellow> to accept!'
  request-sent: '<green>Surrender request successfully sent! You must now wait for the other side to accept or decline it!'
  health-too-high-to-surrender: '<red>You cannot surrender right now! Your health must be lower than or equal to <gold>65 HP</gold>!'
  town-deleted-removed-from-war: '<red>Your town was deleted! You''ve been removed from the war and lost all your lives!'
  mercenary-in-war: '<red>That player is already in a war and cannot be hired as a mercenary!'
  mercenary-request-sent: '<green>Mercenary request successfully sent!'
  no-pending-requests-mercenary: '<red>You don''t have any pending mercenary requests!'
  mercenary-not-online: '<red>That player is offline! You can only hire mercenaries while they''re online!'
  must-specify-money: '<red>You need to specify the money amount for the mercenary!'
  mercenary-hired: '<yellow><mercenary><red> has joined <yellow><entity><red> as a mercenary! They can now participate in the war!'
  mercenary-received: '<yellow><requester><red> has offered you <gold><amount> Gold<red> to join their war as a <yellow>mercenary!<red> Do <yellow>/mercenary accept<red> to accept the offer!'
  # help commands
  townwar-help:
    - "<bold><red>United<white>Wars"
    - "<yellow>/t war scroll <gray><name> <red>- Generates a town war scroll"
    - "<yellow>/t war declare <red>- Declares a war on a town (must hold scroll)"
  nationwar-help:
    - "<bold><red>United<white>Wars"
    - "<yellow>/n war scroll <gray><name> <red>- Generates a nation war scroll"
    - "<yellow>/n war declare <red>- Declares a war on a nation (must hold scroll)"
    - "<yellow>/n war join <red>- Joins another Nation's war, if allies"
  surrender-help:
    - "<bold><red>United<white>Wars"
    - "<yellow>/surrender accept <red>- Accepts any incoming requests"
    - "<yellow>/surrender money <amount> <red>- Sends a surrender request with money"
    - "<yellow>/surrender town <town> <red>- Sends a surrender request with a town (nation wars)"
    - "<yellow>/surrender whitepeace <red>- Sends a white peace request"
    - "<yellow>/surrender none <red>- Surrenders immediately (must have 65 HP)"
  mercenary-help:
    - "<bold><red>United<white>Wars"
    - "<yellow>/mercenary hire <amount> <red>- Hires a mercenary for the given amount of money"
  # Doesn't go through minimessage.
  cannot-do-in-war: '§cYou cannot use this command while in a war.'
  join-war-as-ally: '§cAre you sure you want to help <nation> in their war as an ally?'
  town-purchased-declaration: '§bYour town has just purchased a declaration of war!'
  nation-purchased-declaration: '§bYour nation has just purchased a declaration of war!'
  war-confirmation: '§cAre you sure you want to create a §e<type>§c scroll? This will cost you §e<cost> War tokens§c!'
  war-declare-confirmation: '§cAre you sure you want to declare a §e<type>§c on §e<target>? §cThe war will start immediately after confirmation.'
  surrender-confirm: '§cAre you sure you want to send a surrender request to §e<warring-name>§c? You will lose the war if the request is accepted.'
  surrender-accept-money: '§cAre you sure you want to accept §6<money-amount> Gold§c from §e<surrender-name>§c? Accepting will end the war immediately with you as a winner.'
  surrender-accept-town: '§cAre you sure you want to accept §e<offered-town>§c from §e<surrender-name>§c? Accepting will end the war immediately with you as a winner, and §e<offered-town>§c will become part of your nation.'
  surrender-accept-whitepeace: '§cAre you sure you want to accept the §eWhite Peace§c from §e<surrender-name>§c? Accepting will end the war immediately with you as a winner, however, neither side loses or gains anything.'