masterwork-modifier:
  tips: 0.05
  middle: 0.1
fortification-effects:
  1:
    - HUNGER
    - LUCK
    - JUMP
  2:
    - SPEED
    - SLOW
    - INSTANT_DAMAGE
  3:
    - POISON
    - SLOW_DIGGING
    - FAST_DIGGING
    - ABSORPTION
frenzy-whitelist:
  - DIAMOND_ORE
  - IRON_ORE
  - GOLD_ORE
  - LAPIS_ORE
  - COAL_ORE
  - COPPER_ORE
  - REDSTONE_ORE
  - EMERALD_ORE
  - DEEPSLATE_DIAMOND_ORE
  - DEEPSLATE_IRON_ORE
  - DEEPSLATE_GOLD_ORE
  - DEEPSLATE_LAPIS_ORE
  - DEEPSLATE_COAL_ORE
  - DEEPSLATE_COPPER_ORE
  - DEEPSLATE_REDSTONE_ORE
  - DEEPSLATE_EMERALD_ORE
  - STONE
  - GRANITE
  - ANDESITE
  - DIORITE
  - DEEPSLATE
  - DRIPSTONE_BLOCK
  - CALCITE
  - BASALT
  - BLACKSTONE
brewing-items:
  - FERMENTED_SPIDER_EYE
  - RABBIT_FOOT
  - BLAZE_POWDER
  - MAGMA_CREAM
  - GHAST_TEAR
  - NETHER_WART
  - GLOWSTONE_DUST
  - SPIDER_EYE
  - GOLDEN_CARROT
  - GLISTERING_MELON
  - PUFFERFISH
plant-foods:
  - APPLE
  - MUSHROOM_STEW
  - BREAD
  - COOKIE
  - GOLDEN_APPLE
  - ENCHANTED_GOLDEN_APPLE
  - DRIED_KELP
  - MELON_SLICE
  - CARROT
  - POTATO
  - BAKED_POTATO
  - POISONOUS_POTATO
  - PUMPKIN_PIE
  - BEETROOT
  - BEETROOT_SOUP
  - SWEET_BERRIES
  - GLOW_BERRIES
crop-names:
  - WHEAT
  - CARROTS
  - COCOA
  - BEETROOTS
  - POTATOES
  - MELON
  - PUMPKIN
  - NETHER_WART
potions:
  NIGHT_VISION:
    default: 180
    extended: 480
    upgraded: 180
    max_amplifier: 0
  INVISIBILITY:
    default: 180
    extended: 480
    upgraded: 180
    max_amplifier: 0
  JUMP:
    default: 180
    extended: 480
    upgraded: 90
    max_amplifier: 1
  FIRE_RESISTANCE:
    default: 180
    extended: 480
    upgraded: 180
    max_amplifier: 0
  SPEED:
    default: 180
    extended: 480
    upgraded: 90
    max_amplifier: 1
  SLOWNESS:
    default: 90
    extended: 240
    upgraded: 20
    max_amplifier: 3
  WATER_BREATHING:
    default: 180
    extended: 480
    upgraded: 180
    max_amplifier: 0
  POISON:
    default: 45
    extended: 90
    upgraded: 21
    max_amplifier: 1
  REGEN:
    default: 45
    extended: 90
    upgraded: 22
    max_amplifier: 1
  STRENGTH:
    default: 180
    extended: 480
    upgraded: 90
    max_amplifier: 1
  WEAKNESS:
    default: 90
    extended: 240
    upgraded: 90
    max_amplifier: 0
  LUCK:
    default: 300
    extended: 300
    upgraded: 300
    max_amplifier: 0
  SLOW_FALLING:
    default: 90
    extended: 240
    upgraded: 90
    max_amplifier: 0
  CONFUSION:
    default: 90
    extended: 240
    upgraded: 90
    max_amplifier: 0
  SATURATION:
    default: 90
    extended: 240
    upgraded: 90
    max_amplifier: 0
  INSTANT_HEAL:
    default: 0
    extended: 0
    upgraded: 0
    max_amplifier: 1
  INSTANT_DAMAGE:
    default: 0
    extended: 0
    upgraded: 0
    max_amplifier: 1
wrangler-mobs:
  - PIG
  - COW
  - CHICKEN
  - HORSE
  - SHEEP
  - AXOLOTL
  - BAT
  - BEE
  - CAT
  - DOLPHIN
  - DONKEY
  - FOX
  - GLOW_SQUID
  - GOAT
  - LLAMA
  - MOOSHROOM
  - MULE
  - OCELOT
  - PANDA
  - PARROT
  - POLAR_BEAR
  - RABBIT
  - SQUID
  - STRIDER
  - TRADER_LLAMA
  - TURTLE
  - WOLF
trafficker-mobs:
  - BLAZE
  - CAVE_SPIDER
  - CREEPER
  - SPIDER
  - ENDERMAN
  - ENDERMITE
  - GHAST
  - GUARDIAN
  - HOGLIN
  - HUSK
  - MAGMA_CUBE
  - PHANTOM
  - PIGLIN
  - PIGLIN_BRUTE
  - SILVERFISH
  - SKELETON
  - SLIME
  - SPIDER
  - STRAY
  - VEX
  - WITCH
  - WITHER_SKELETON
  - ZOGLIN
  - ZOMBIE
  - ZOMBIFIED_PIGLIN
excavator-items:
  - DIRT
  - SAND
  - GRAVEL
  - SOUL_SAND
  - SOUL_SOIL
  - ROOTED_DIRT
  - COARSE_DIRT
  - GRASS_BLOCK
  - RED_SAND
  - MYCELIUM
  - PODZOL
archaeologist-loot:
  diamond:
    material: DIAMOND
    chance: 0.001
    min: 1
    max: 1
    required-level: 3
    level-modifier: 0.0
    blocks:
      - DIRT
      - ROOTED_DIRT
      - GRASS_BLOCK
      - PODZOL
      - COARSE_DIRT
      - FARMLAND
  emerald:
    material: EMERALD
    chance: 0.001
    min: 1
    max: 1
    required-level: 3
    level-modifier: 0.0
    blocks:
      - DIRT
      - ROOTED_DIRT
      - GRASS_BLOCK
      - PODZOL
      - COARSE_DIRT
      - FARMLAND
  turtle_egg:
    material: TURTLE_EGG
    chance: 0.001
    min: 1
    max: 1
    required-level: 3
    level-modifier: 0.0
    blocks:
      - SAND
  raw_gold:
    material: RAW_GOLD
    chance: 0.005
    min: 1
    max: 4
    required-level: 3
    level-modifier: 0.0
    blocks:
      - RED_SAND
  raw_gold2:
    material: RAW_GOLD
    chance: 0.005
    min: 1
    max: 4
    required-level: 3
    level-modifier: 0.0
    blocks:
      - GRAVEL
  gunpowder:
    material: GUNPOWDER
    chance: 0.0025
    min: 2
    max: 6
    required-level: 3
    level-modifier: 0.0
    blocks:
      - GRAVEL
  nautilus_shell:
    material: NAUTILUS_SHELL
    chance: 0.003
    min: 1
    max: 1
    required-level: 3
    level-modifier: 0.0
    blocks:
      - CLAY
  wither_skull:
    material: WITHER_SKELETON_SKULL
    chance: 0.0001
    min: 1
    max: 1
    required-level: 3
    level-modifier: 0.0
    blocks:
      - SOUL_SAND
      - SOUL_SOIL
  corals:
    materials:
      - TUBE_CORAL
      - BRAIN_CORAL
      - BUBBLE_CORAL
      - FIRE_CORAL
      - HORN_CORAL
    chance: 0.005
    min: 1
    max: 3
    required-level: 2
    level-modifier: 0.0
    blocks:
      - SAND
  magma_cream:
    material: MAGMA_CREAM
    chance: 0.005
    min: 1
    max: 3
    required-level: 3
    level-modifier: 0.0
    blocks:
      - SOUL_SAND
      - SOUL_SOIL
  lapis:
    material: LAPIS_LAZULI
    chance: 0.005
    min: 1
    max: 2
    required-level: 2
    level-modifier: 0.01
    blocks:
      - DIRT
      - ROOTED_DIRT
      - GRASS_BLOCK
      - PODZOL
      - COARSE_DIRT
      - FARMLAND
  scute:
    material: SCUTE
    chance: 0.005
    min: 1
    max: 1
    required-level: 2
    level-modifier: 0.0
    blocks:
      - SAND
  gold_ingot:
    material: GOLD_INGOT
    chance: 0.001
    min: 1
    max: 2
    required-level: 2
    level-modifier: 0.0
    blocks:
      - RED_SAND
  raw_copper:
    material: RAW_COPPER
    chance: 0.003
    min: 1
    max: 2
    required-level: 2
    level-modifier: 0.0
    blocks:
      - GRAVEL
  brick:
    material: BRICK
    chance: 0.003
    min: 1
    max: 2
    required-level: 2
    level-modifier: 0.0
    blocks:
      - GRAVEL
  prismarine_crystal:
    material: PRISMARINE_CRYSTAL
    chance: 0.005
    min: 1
    max: 2
    required-level: 2
    level-modifier: 0.0
    blocks:
      - CLAY
  gold_nugget2:
    material: GOLD_NUGGET
    chance: 0.005
    min: 1
    max: 4
    required-level: 2
    level-modifier: 0.0
    blocks:
      - SOUL_SAND
      - SOUL_SOIL
  blaze_rod:
    material: BLAZE_ROD
    chance: 0.005
    min: 1
    max: 2
    required-level: 2
    level-modifier: 0.0
    blocks:
      - SOUL_SAND
      - SOUL_SOIL
  coal:
    material: COAL
    chance: 0.001
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.01
    blocks:
      - DIRT
      - ROOTED_DIRT
      - GRASS_BLOCK
      - PODZOL
      - COARSE_DIRT
      - FARMLAND
  charcoal:
    material: CHARCOAL
    chance: 0.001
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.01
    blocks:
      - DIRT
      - ROOTED_DIRT
      - GRASS_BLOCK
      - PODZOL
      - COARSE_DIRT
      - FARMLAND
  gold_nuggets:
    material: GOLD_NUGGET
    chance: 0.003
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.0
    blocks:
      - RED_SAND
  raw_iron:
    material: RAW_IRON
    chance: 0.003
    min: 1
    max: 2
    required-level: 1
    level-modifier: 0.0
    blocks:
      - GRAVEL
  prismarine_shard:
    material: PRISMARINE_SHARD
    chance: 0.005
    min: 1
    max: 1
    required-level: 1
    level-modifier: 0.0
    blocks:
      - CLAY
  quartz:
    material: QUARTZ
    chance: 0.005
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.0
    blocks:
      - SOUL_SAND
      - SOUL_SOIL
  glowstone_dust:
    material: GLOWSTONE_DUST
    chance: 0.005
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.0
    blocks:
      - SOUL_SAND
      - SOUL_SOIL
  red_mushroom:
    material: RED_MUSHROOM
    chance: 0.005
    min: 1
    max: 2
    required-level: 1
    level-modifier: 0.0
    blocks:
      - MYCELIUM
  brown_mushroom:
    material: BROWN_MUSHROOM
    chance: 0.005
    min: 1
    max: 2
    required-level: 1
    level-modifier: 0.0
    blocks:
      - MYCELIUM
mineral-finder-loot:
  maronine:
    material: PAPER
    name: "&eMaronine Nugget"
    min: 1
    max: 1
    chance: 0.005
    required-level: 1
    level-modifier: 0.0
    custom-model-data: 1
    blocks:
      - SOUL_SAND
      - SOUL_SOIL
  litnium:
    material: PAPER
    chance: 0.005
    min: 1
    max: 2
    required-level: 2
    custom-model-data: 2
    name: "&eLitnium Nugget"
    level-modifier: 0.0
    blocks:
      - DIRT
      - ROOTED_DIRT
      - GRASS
      - PODZOL
      - COARSE_DIRT
      - FARMLAND
  cinnarite:
    material: GOLD_NUGGET
    chance: 0.005
    min: 1
    max: 1
    required-level: 3
    custom-model-data: 3
    name: "&eCinnarite Nugget"
    level-modifier: 0.0
    blocks:
      - SAND
      - RED_SAND
rare-catch-loot:
  riverfish:
    name: "&eRiverfish"
    material: COD
    chance: 0.05
    min: 1
    max: 1
    required-level: 1
    level-modifier: 0.0
    custom-model-data: 1
    biomes:
      - RIVER
  shimmerfish:
    name: "&eShimmerfish"
    material: COD
    chance: 0.05
    min: 1
    max: 1
    required-level: 2
    level-modifier: 0.0
    custom-model-data: 2
    biomes:
      - WARM_OCEAN
  icefish:
    name: "&eIcefish"
    material: COD
    chance: 0.05
    min: 1
    max: 1
    required-level: 3
    level-modifier: 0.0
    custom-model-data: 3
    biomes:
      - FROZEN_OCEAN
      - FROZEN_RIVER
      - DEEP_FROZEN_OCEAN
treasure-hunter-loot:
  prismarine_crystal:
    material: PRISMARINE_CRYSTAL
    chance: 0.02
    min: 1
    max: 2
    required-level: 3
    level-modifier: 0.0
  quartz:
    material: QUARTZ
    chance: 0.01
    min: 1
    max: 4
    required-level: 3
    level-modifier: 0.0
  diamond:
    material: DIAMOND
    chance: 0.01
    min: 1
    max: 2
    required-level: 3
    level-modifier: 0.0
  emerald:
    material: EMERALD
    chance: 0.02
    min: 1
    max: 2
    required-level: 3
    level-modifier: 0.0
  ender_pearl:
    material: ENDER_PEARL
    chance: 0.02
    min: 1
    max: 2
    required-level: 3
    level-modifier: 0.0
  netherite_stuff:
    materials:
      - NETHERITE_HELMET
      - NETHERITE_CHESTPLATE
      - NETHERITE_BOOTS
      - NETHERITE_LEGGINGS
      - NETHERITE_SWORD
      - NETHERITE_AXE
      - NETHERITE_HOE
      - NETHERITE_SHOVEL
      - NETHERITE_PICKAXE
    chance: 0.005
    min: 1
    max: 1
    required-level: 3
    level-modifier: 0.0
    random-damage: true
  gold_ingot:
    material: GOLD_INGOT
    chance: 0.03
    min: 1
    max: 3
    required-level: 2
    level-modifier: 0.0
  prismarine_shard:
    material: PRISMARINE_SHARD
    chance: 0.03
    min: 1
    max: 3
    required-level: 2
    level-modifier: 0.0
  corals:
    materials:
      - TUBE_CORAL
      - BRAIN_CORAL
      - BUBBLE_CORAL
      - FIRE_CORAL
      - HORN_CORAL
    chance: 0.03
    min: 1
    max: 3
    required-level: 2
    level-modifier: 0.0
  heart_of_the_sea:
    material: HEART_OF_THE_SEA
    chance: 0.01
    min: 1
    max: 1
    required-level: 2
    level-modifier: 0.0
  diamond_stuff:
    materials:
      - DIAMOND_HELMET
      - DIAMOND_CHESTPLATE
      - DIAMOND_BOOTS
      - DIAMOND_LEGGINGS
      - DIAMOND_SWORD
      - DIAMOND_AXE
      - DIAMOND_HOE
      - DIAMOND_SHOVEL
      - DIAMOND_PICKAXE
    chance: 0.01
    min: 1
    max: 1
    required-level: 2
    level-modifier: 0.0
    random-damage: true
  lapis:
    material: LAPIS_LAZULI
    chance: 0.03
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.01
  iron_ingot:
    material: IRON_INGOT
    chance: 0.03
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.0
  copper_ingot:
    material: COPPER_INGOT
    chance: 0.03
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.0
  coal:
    material: COAL
    chance: 0.03
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.0
  nautilus_shell:
    material: NAUTILUS_SHELL
    chance: 0.04
    min: 1
    max: 1
    required-level: 1
    level-modifier: 0.01
  disks:
    chance: 0.01
    materials:
      - MUSIC_DISK_13
      - MUSIC_DISK_CAT
      - MUSIC_DISK_BLOCKS
      - MUSIC_DISK_CHIRP
      - MUSIC_DISK_FAR
      - MUSIC_DISK_MALL
      - MUSIC_DISK_MELLOHI
      - MUSIC_DISK_STAL
      - MUSIC_DISK_STRAD
      - MUSIC_DISK_WARD
      - MUSIC_DISK_11
      - MUSIC_DISK_WAIT
      - MUSIC_DISK_OTHERSIDE
      - MUSIC_DISK_PIGSTEP
    min: 1
    max: 1
    required-level: 1
    level-modifier: 0.0
biome-kit:
  nether-biomes:
    - CRIMSON_FOREST;CRIMSON_FUNGUS;#A42020
    - BASALT_DELTAS;BASALT;#6D6767
    - SOUL_SAND_VALLEY;SOUL_SAND;#4F3E25
    - NETHER_WASTES;NETHERRACK;#BD341D
    - WARPED_FOREST;WARPED_FUNGUS;#11869E
  overworld-biomes:
    - BADLANDS;TERRACOTTA;#A9540D
    - BAMBOO_JUNGLE;BAMBOO;#4AA72A
    - BEACH;SAND;#E4E191
    - BIRCH_FOREST;BIRCH_LOG;#DCDCCF
    - DARK_FOREST;DARK_OAK_LOG;#634005
    - DEEP_OCEAN;WATER_BUCKET;#214A91
    - DESERT;SAND;#E4E191
    - DRIPSTONE_CAVES;POINTED_DRIPSTONE;#8A7D5A
    - FLOWER_FOREST;ROSE_BUSH;#C41111
    - FOREST;OAK_LOG;#60B22A
    - FROZEN_OCEAN;ICE;#18C6DB
    - ICE_SPIKES;PACKED_ICE;#18C6DB
    - GROVE;SNOW_BLOCK;#FFFFFF
    - JUNGLE;JUNGLE_LOG;#05851F
    - LUKEWARM_OCEAN;WATER_BUCKET;#11B7B4
    - LUSH_CAVES;FLOWERING_AZALEA;#A8DE50
    - MEADOW;WHEAT;#E7BF19
    - MUSHROOM_FIELDS;RED_MUSHROOM;#CC745B
    - OCEAN;WATER_BUCKET;#4985BC
    - PLAINS;GRASS_BLOCK;#94CC23
    - SNOWY_PLAINS;SNOW;#FFFFFF
    - RIVER;INK_SAC;#238FCC
    - SAVANNA;ACACIA_LOG;#C88838
    - SWAMP;VINE;#316E3F
    - TAIGA;SPRUCE_LOG;#524225
    - WARM_OCEAN;TROPICAL_FISH_BUCKET;#52E9D2
    - WINDSWEPT_HILLS;STONE;#CCCCCC
messages:
  no-permission: "You do not have permission to execute this command!"
  must-be-hunter: "<red>You must be a hunter with the <yellow>Trafficker Skill<red> to use this safari net on this entity!"
  must-be-farmer: "<red>You must be a farmer with the <yellow>Wrangler Skill<red> to use this safari net on this entity!"
  biome-selected: "<green>Biome successfully selected!"
  biome-changed: "<green>Chunk biome successfully changed! <gray>You must leave the area to see changes!"
  choose-biome-first: "<red>You must choose a biome first!"
  points-available: "<bold><red>U<white>L </bold><dark_gray>Â»<red> You have <white><points><red> available!"